# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'interface.ui'
##
## Created by: Qt User Interface Compiler version 6.5.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QFrame,
    QLabel, QProgressBar, QPushButton, QSizePolicy,
    QWidget, QDialog)

from pyqtgraph import PlotWidget

class Ui_Dialog(QObject):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(744, 878)
        self.active_progress_bar = QProgressBar(Dialog)
        self.active_progress_bar.setObjectName(u"active_progress_bar")
        self.active_progress_bar.setGeometry(QRect(460, 130, 118, 23))
        self.active_progress_bar.setValue(0)
        self.sensor_selector = QComboBox(Dialog)
        self.sensor_selector.addItem("")
        self.sensor_selector.addItem("")
        self.sensor_selector.addItem("")
        self.sensor_selector.setObjectName(u"sensor_selector")
        self.sensor_selector.setGeometry(QRect(350, 160, 181, 31))
        self.sensor_selector.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.acc_sampling_label = QLabel(Dialog)
        self.acc_sampling_label.setObjectName(u"acc_sampling_label")
        self.acc_sampling_label.setGeometry(QRect(120, 180, 81, 31))
        self.acc_sensitivity = QComboBox(Dialog)
        self.acc_sensitivity.addItem("")
        self.acc_sensitivity.addItem("")
        self.acc_sensitivity.addItem("")
        self.acc_sensitivity.addItem("")
        self.acc_sensitivity.setObjectName(u"acc_sensitivity")
        self.acc_sensitivity.setGeometry(QRect(210, 130, 104, 31))
        self.acc_sensitivity_label = QLabel(Dialog)
        self.acc_sensitivity_label.setObjectName(u"acc_sensitivity_label")
        self.acc_sensitivity_label.setGeometry(QRect(120, 130, 81, 31))
        self.title = QLabel(Dialog)
        self.title.setObjectName(u"title")
        self.title.setGeometry(QRect(320, 40, 91, 41))
        self.title.setLayoutDirection(Qt.LeftToRight)
        self.title.setFrameShape(QFrame.Box)
        self.title.setAlignment(Qt.AlignCenter)
        self.acc_sampling = QComboBox(Dialog)
        self.acc_sampling.addItem("")
        self.acc_sampling.addItem("")
        self.acc_sampling.addItem("")
        self.acc_sampling.addItem("")
        self.acc_sampling.addItem("")
        self.acc_sampling.addItem("")
        self.acc_sampling.addItem("")
        self.acc_sampling.addItem("")
        self.acc_sampling.addItem("")
        self.acc_sampling.addItem("")
        self.acc_sampling.addItem("")
        self.acc_sampling.addItem("")
        self.acc_sampling.setObjectName(u"acc_sampling")
        self.acc_sampling.setGeometry(QRect(210, 180, 104, 31))
        self.mode_selector = QComboBox(Dialog)
        self.mode_selector.addItem("")
        self.mode_selector.addItem("")
        self.mode_selector.setObjectName(u"mode_selector")
        self.mode_selector.setGeometry(QRect(360, 300, 181, 31))
        self.mode_selector.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.mode_selector_label = QLabel(Dialog)
        self.mode_selector_label.setObjectName(u"mode_selector_label")
        self.mode_selector_label.setGeometry(QRect(370, 270, 151, 21))
        self.mode_selector_label.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"\n"
"")
        self.accelerometer_title = QLabel(Dialog)
        self.accelerometer_title.setObjectName(u"accelerometer_title")
        self.accelerometer_title.setGeometry(QRect(170, 100, 121, 21))
        self.accelerometer_title.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"\n"
"")
        self.gyroscope_title = QLabel(Dialog)
        self.gyroscope_title.setObjectName(u"gyroscope_title")
        self.gyroscope_title.setGeometry(QRect(170, 220, 121, 21))
        self.gyroscope_title.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"\n"
"")
        self.gyr_sensitivity_label = QLabel(Dialog)
        self.gyr_sensitivity_label.setObjectName(u"gyr_sensitivity_label")
        self.gyr_sensitivity_label.setGeometry(QRect(120, 250, 81, 31))
        self.gyr_sampling_label = QLabel(Dialog)
        self.gyr_sampling_label.setObjectName(u"gyr_sampling_label")
        self.gyr_sampling_label.setGeometry(QRect(120, 300, 81, 31))
        self.gyr_sampling = QComboBox(Dialog)
        self.gyr_sampling.addItem("")
        self.gyr_sampling.addItem("")
        self.gyr_sampling.addItem("")
        self.gyr_sampling.addItem("")
        self.gyr_sampling.addItem("")
        self.gyr_sampling.addItem("")
        self.gyr_sampling.addItem("")
        self.gyr_sampling.addItem("")
        self.gyr_sampling.setObjectName(u"gyr_sampling")
        self.gyr_sampling.setGeometry(QRect(210, 300, 104, 31))
        self.gyr_sensitivity = QComboBox(Dialog)
        self.gyr_sensitivity.addItem("")
        self.gyr_sensitivity.addItem("")
        self.gyr_sensitivity.addItem("")
        self.gyr_sensitivity.addItem("")
        self.gyr_sensitivity.addItem("")
        self.gyr_sensitivity.setObjectName(u"gyr_sensitivity")
        self.gyr_sensitivity.setGeometry(QRect(210, 250, 104, 31))
        self.Plot1 = PlotWidget(Dialog)
        self.Plot1.setObjectName(u"Plot1")
        self.Plot1.setGeometry(QRect(60, 420, 291, 181))
        self.Plot1.setFrameShape(QFrame.Box)
        self.Plot1.setFrameShadow(QFrame.Plain)
        self.Plot2 = PlotWidget(Dialog)
        self.Plot2.setObjectName(u"Plot2")
        self.Plot2.setGeometry(QRect(390, 420, 291, 181))
        self.Plot2.setFrameShape(QFrame.Box)
        self.Plot2.setFrameShadow(QFrame.Plain)
        self.Plot3 = PlotWidget(Dialog)
        self.Plot3.setObjectName(u"Plot3")
        self.Plot3.setGeometry(QRect(60, 640, 291, 181))
        self.Plot3.setFrameShape(QFrame.Box)
        self.Plot3.setFrameShadow(QFrame.Plain)
        self.Plot4 = PlotWidget(Dialog)
        self.Plot4.setObjectName(u"Plot4")
        self.Plot4.setGeometry(QRect(390, 640, 291, 181))
        self.Plot4.setFrameShape(QFrame.Box)
        self.Plot4.setFrameShadow(QFrame.Plain)
        self.plot1_label = QLabel(Dialog)
        self.plot1_label.setObjectName(u"plot1_label")
        self.plot1_label.setGeometry(QRect(120, 390, 151, 21))
        self.plot1_label.setLayoutDirection(Qt.LeftToRight)
        self.plot1_label.setFrameShape(QFrame.Box)
        self.plot1_label.setAlignment(Qt.AlignCenter)
        self.plot2_label = QLabel(Dialog)
        self.plot2_label.setObjectName(u"plot2_label")
        self.plot2_label.setGeometry(QRect(440, 390, 151, 21))
        self.plot2_label.setLayoutDirection(Qt.LeftToRight)
        self.plot2_label.setFrameShape(QFrame.Box)
        self.plot2_label.setAlignment(Qt.AlignCenter)
        self.plot3_label = QLabel(Dialog)
        self.plot3_label.setObjectName(u"plot3_label")
        self.plot3_label.setGeometry(QRect(120, 610, 151, 21))
        self.plot3_label.setLayoutDirection(Qt.LeftToRight)
        self.plot3_label.setFrameShape(QFrame.Box)
        self.plot3_label.setAlignment(Qt.AlignCenter)
        self.plot4_label = QLabel(Dialog)
        self.plot4_label.setObjectName(u"plot4_label")
        self.plot4_label.setGeometry(QRect(440, 610, 151, 21))
        self.plot4_label.setLayoutDirection(Qt.LeftToRight)
        self.plot4_label.setFrameShape(QFrame.Box)
        self.plot4_label.setAlignment(Qt.AlignCenter)
        self.update_config = QPushButton(Dialog)
        self.update_config.setObjectName(u"update_config")
        self.update_config.setGeometry(QRect(550, 160, 141, 31))
        self.start_data_capture = QPushButton(Dialog)
        self.start_data_capture.setObjectName(u"start_data_capture")
        self.start_data_capture.setGeometry(QRect(320, 370, 101, 41))
        self.active_progress_label = QLabel(Dialog)
        self.active_progress_label.setObjectName(u"active_progress_label")
        self.active_progress_label.setGeometry(QRect(360, 120, 91, 31))

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.sensor_selector.setItemText(0, QCoreApplication.translate("Dialog", u"<None>", None))
        self.sensor_selector.setItemText(1, QCoreApplication.translate("Dialog", u"BMI270", None))
        self.sensor_selector.setItemText(2, QCoreApplication.translate("Dialog", u"BME688", None))

        self.acc_sampling_label.setText(QCoreApplication.translate("Dialog", u"Frecuencia de \n"
" muestreo", None))
        self.acc_sensitivity.setItemText(0, QCoreApplication.translate("Dialog", u"+/- 2g", None))
        self.acc_sensitivity.setItemText(1, QCoreApplication.translate("Dialog", u"+/- 4g", None))
        self.acc_sensitivity.setItemText(2, QCoreApplication.translate("Dialog", u"+/- 8g", None))
        self.acc_sensitivity.setItemText(3, QCoreApplication.translate("Dialog", u"+/- 16g", None))

        self.acc_sensitivity_label.setText(QCoreApplication.translate("Dialog", u"Sensibilidad", None))
        self.title.setText(QCoreApplication.translate("Dialog", u"Configuracion \n"
" Sensor", None))
        self.acc_sampling.setItemText(0, QCoreApplication.translate("Dialog", u"25/32", None))
        self.acc_sampling.setItemText(1, QCoreApplication.translate("Dialog", u"25/16", None))
        self.acc_sampling.setItemText(2, QCoreApplication.translate("Dialog", u"25/8", None))
        self.acc_sampling.setItemText(3, QCoreApplication.translate("Dialog", u"25/4", None))
        self.acc_sampling.setItemText(4, QCoreApplication.translate("Dialog", u"25/2", None))
        self.acc_sampling.setItemText(5, QCoreApplication.translate("Dialog", u"25", None))
        self.acc_sampling.setItemText(6, QCoreApplication.translate("Dialog", u"50", None))
        self.acc_sampling.setItemText(7, QCoreApplication.translate("Dialog", u"100", None))
        self.acc_sampling.setItemText(8, QCoreApplication.translate("Dialog", u"200", None))
        self.acc_sampling.setItemText(9, QCoreApplication.translate("Dialog", u"400", None))
        self.acc_sampling.setItemText(10, QCoreApplication.translate("Dialog", u"800", None))
        self.acc_sampling.setItemText(11, QCoreApplication.translate("Dialog", u"1600", None))

        self.mode_selector.setItemText(0, QCoreApplication.translate("Dialog", u"Paralelo", None))
        self.mode_selector.setItemText(1, QCoreApplication.translate("Dialog", u"Forzado", None))

        self.mode_selector_label.setText(QCoreApplication.translate("Dialog", u"Modo de Funcionamiento", None))
        self.accelerometer_title.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" text-decoration: underline;\">Aceler\u00f3metro</span></p></body></html>", None))
        self.gyroscope_title.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" text-decoration: underline;\">Giroscopio</span></p></body></html>", None))
        self.gyr_sensitivity_label.setText(QCoreApplication.translate("Dialog", u"Sensibilidad", None))
        self.gyr_sampling_label.setText(QCoreApplication.translate("Dialog", u"Frecuencia de \n"
" muestreo", None))
        self.gyr_sampling.setItemText(0, QCoreApplication.translate("Dialog", u"25", None))
        self.gyr_sampling.setItemText(1, QCoreApplication.translate("Dialog", u"50", None))
        self.gyr_sampling.setItemText(2, QCoreApplication.translate("Dialog", u"100", None))
        self.gyr_sampling.setItemText(3, QCoreApplication.translate("Dialog", u"200", None))
        self.gyr_sampling.setItemText(4, QCoreApplication.translate("Dialog", u"400", None))
        self.gyr_sampling.setItemText(5, QCoreApplication.translate("Dialog", u"800", None))
        self.gyr_sampling.setItemText(6, QCoreApplication.translate("Dialog", u"1600", None))
        self.gyr_sampling.setItemText(7, QCoreApplication.translate("Dialog", u"3200", None))

        self.gyr_sensitivity.setItemText(0, QCoreApplication.translate("Dialog", u"+/- 2000dps", None))
        self.gyr_sensitivity.setItemText(1, QCoreApplication.translate("Dialog", u"+/- 1000dps", None))
        self.gyr_sensitivity.setItemText(2, QCoreApplication.translate("Dialog", u"+/- 500dps", None))
        self.gyr_sensitivity.setItemText(3, QCoreApplication.translate("Dialog", u"+/- 250dps", None))
        self.gyr_sensitivity.setItemText(4, QCoreApplication.translate("Dialog", u"+/- 125dps", None))

        self.plot1_label.setText(QCoreApplication.translate("Dialog", u"Datos 1: <Datos>", None))
        self.plot2_label.setText(QCoreApplication.translate("Dialog", u"Datos 2: <Datos>", None))
        self.plot3_label.setText(QCoreApplication.translate("Dialog", u"Datos 3: <Datos>", None))
        self.plot4_label.setText(QCoreApplication.translate("Dialog", u"Datos 4: <Datos>", None))
        self.update_config.setText(QCoreApplication.translate("Dialog", u"Iniciar configuraci\u00f3n", None))
        self.start_data_capture.setText(QCoreApplication.translate("Dialog", u"Iniciar captaci\u00f3n \n"
" de datos", None))
        self.active_progress_label.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"center\"><span style=\" text-decoration: underline;\">Sensor activo</span></p></body></html>", None))
    # retranslateUi

